---
title: "Evaluating Models"
author: "Margaret Brickner, Anna Abelman, Rich Viebrock"
date: "5/20/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(purrr)
library(lubridate)
library(ggplot2)
source("nse.R")
```


### Question 01: Code your metric as a function

```{r}
# We picked winter streamflow (11,12,1,2)
source("performance_metric.R")
```

### Question 02: Apply to the streamflow data provided in sagerm.txt (multiple model results)

```{r performance metric}
# read in sager data
# -----------------------------------------------------------------------------
sager = read.table("sager.txt", header=T) %>% 
  mutate(date=make_date(year=year, month=month, day=day))

# now read in the model outputs
# -----------------------------------------------------------------------------
sagerm = read.table("sagerm.txt", header = T) %>% 
  mutate(date = sager$date,
         month = sager$month, 
         year = sager$year,
         day = sager$day,
         wy = sager$wy,
         obs = sager$obs)

# call in and run function using sager data
# -----------------------------------------------------------------------------

winter_flow(m = sagerm$m, 
            o = sagerm$o, 
            month = sagerm$month, 
            year = sagerm$year, 
            wy = sagerm$wy)
```

### Question 03: Find the simulation that gives the best performance (record that and add to the quiz on gauchospace)

```{r best simulation}
# to turn all the columns of different outputs into a single column identified by "run"
# -----------------------------------------------------------------------------
sagerml = sagerm %>% 
  gather(key="run",
         value="streamflow", 
         -date, -month, -day, -year, -wy, -obs)

# compute performance measures for all output
# -----------------------------------------------------------------------------
res = sagerm %>% 
  select(-date, -month, -day, -year, -wy,-obs ) %>%
  map_dbl(~nse(m=.x, o=sagerm$obs))

summary(res)
sims = names(sagerm %>% select(-date, -month, -day,-year,-wy, -obs))
results = cbind.data.frame(simnames=sims, nse=res)

# another example using our low flow statistics
# use apply to compute for all the data
# -----------------------------------------------------------------------------
res = sagerm %>% 
  select(-date, -month, -day, -year, -wy, -obs) %>% 
  map_dbl(~winter_flow(o=sagerm$obs, month=sagerm$month, 
                        year=sagerm$year, wy=sagerm$wy, m=.x))
# add to our results
# -----------------------------------------------------------------------------
results$cor = res
answer_03 = max(results$cor)

# put this in a format that's easy to compare
# use which.min and convert all to positive values to find the closest match
# -----------------------------------------------------------------------------
resultsl = results %>% 
  gather(key="metric",value="value", -simnames)

which.min(abs(0 - resultsl$value))

# For us the closest simulation was V168

```

### Question 04: Create a boxplot of your metric applied to sagerm.txt

```{r graphing}
# graph range of performance measures

ggplot(resultsl, aes(metric, value))+
  geom_boxplot()+
  facet_wrap(~metric, scales="free") +
  labs(title = "Streamflow Model Evaluation", x = "Metric", y = "Value") + 
  theme_bw()

ggsave("evaluating_models.png")

# are metrics related to each other
# useful for assessing whether there are tradeoffs
# -----------------------------------------------------------------------------
ggplot(results, aes(cor, nse))+geom_point()
```

### Question 05: Submit metric function and boxplot on gauchospace